# Generated by Django 5.1.1 on 2024-09-23 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConverationMessage',
            new_name='ConversationMessage',
        ),
    ]
